### ISSUE TITLE
見た目の修正をする箇所をリストアップする

### ISSUE THREAD

**Issue by chihaso** [takuya-ookuchi/books-manager#54]
- ナビゲーションバーorサイドバーを整える
- 各ページ、ボタンの配置を整える
- セレクトボックスの大きさを調整する
- 検索フォームの配置を整える
- 一覧のリンクに`Stretched link`を使う
- バリデーションエラーの見た目を変更する。

**Comment by ledsun** [comment]
## 一覧画面

![image](https://user-images.githubusercontent.com/1079508/151917126-237993f0-d4e8-4ae5-9d7a-4b59cfb88f95.png)
- 「書籍一覧」の真下に「新規登録」ボタンがあるのは変な感じがします。
-  タイトルの入力欄が絞り込み検索の欄だとわかりにくいです。上とも関連して新規登録の欄か検索の欄か間違えやすいです。

## 書籍登録画面

書籍登録後に書籍詳細画面に遷移するのは変かも？一覧に戻った方がいい？登録してすぐ借りたいから今のままがいい？

## 書籍詳細画面

![image](https://user-images.githubusercontent.com/1079508/151917686-65b23b7f-1882-4f77-b8a5-3fa66ffd7d69.png)


- 貸し出し後に一覧画面に遷移するのは変かも？一覧に貸し出し状態が表示されたらいいのかも？あとでもう一回みる。
- 「借りる」ボタン、「編集」「削除」ボタンの配置は工夫したい。どれとどれがグループかわかりにくいです。
- ユーザー名をクリックするとエラーがおきます。

![42d1499ec3757656ac2a7a28b481bc5d](https://user-images.githubusercontent.com/1079508/151917912-4eac0839-9d1d-42f0-8dd4-41f9f97df363.gif)

**Comment by KishiKyousuke** [comment]
- 「編集」ボタンの色は「借りる」や「新規作成」ボタンの色と変えたほうがわかりやそう
- 検索ボックスや、新規作成時のテキストフィールドにプレースホルダーを使うと良いかも
- 個人的にですが、他ページへのリンクが右上だとちょっと遠く感じる

**Comment by ledsun** [comment]
#66 #67 #68 に分割したのでクローズします。
