### ISSUE TITLE
ボタンを整える

### ISSUE THREAD

**Issue by takuya-ookuchi** [takuya-ookuchi/books-manager#66]
- 編集ボタンの色を変更
- 各ヘージボタンの配置を変更

**Comment by chihaso** [comment]
書籍の個別ページついて
  - 編集ボタンを書籍タイトルの横に置く
  - 削除ボタンは貸し出し履歴の下に置く
  - 借りるボタンは大きくできるなら大きくする
  - 編集ボタンと借りるボタンの色を変える（いくつかの案をslackでスクショ共有）
  - 借りるボタン、検索ボタンはフォームの右横に
